#stage1
FROM maven:3.9.6-eclipse-temurin-17 AS builder
WORKDIR /app
COPY . .
RUN mvn package -DskipTests


#stage2
FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY --from=builder /app/target/demo-0.0.1-SNAPSHOT.jar app.jar
Expose 8080
CMD ["java", "-jar", "app.jar"]
